4770 Create a custom behavior for paraghrap which switch image align …
ChesterDrupal/Study pull request #26
Opened 2022-05-26 15:18 UTC by ChesterDrupal

…+ install and configurate xdebug
https://redmine.devbranch.work/issues/4770
Create a custom behavior for paraghrap which switch image align
Install and configurate xdebug

2022-05-28 08:19 UTC, Y0r requested changes
A lot of problems, need to solve before merging.

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/paragraph_align.routing.yml
> +    _title: 'Welcome to My Module in Drupal 9'
Is this title good for this page? In my opinion, it should describe related functionality.

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/paragraph_align.routing.yml
> +    _controller: '\Drupal\paragraph_align\Controller\ParagraphController::para'
The controller name is okay, but the method name is weird.

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/paragraph_align.routing.yml
> +  path: '/paragraph/page'
Will be better: /admin/paragraphs/align

1) Management pages should be in /admin section
2) Path should be simple and describe the goal

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Controller/ParagraphController.php
> +namespace Drupal\paragraph_align\Controller;
Why do you need this code? 
Better to remove useless code.

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Controller/ParagraphController.php
> +namespace Drupal\paragraph_align\Controller;
Let's discuss it in monday

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> +class imagealign extends ParagraphsBehaviorBase {
Class name should be in CamelCase

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> + *   id = "dummy_image_and_text",
Wrong identifier of the plugin. 
I think should be 'image_text_align' or something like that.

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> + *   description = @Translation("Allows to select image size and position."),
Nope, wrong description. Is it copy-paste code?

2022-05-28 08:19 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> +    $summary = [];
This line is useless.

2022-05-28 08:19 UTC, Y0r commented on web/themes/custom/bart/src/scss/MainCategoryPage.scss
> +// Header of category page.7373
Have a look at this comment I think something wrong with it.

2022-06-07 08:46 UTC, ChesterDrupal commented
Resolved all issues.

2022-06-07 12:10 UTC, Y0r commented on web/modules/custom/paragraph_align/paragraph_align.routing.yml
> +  path: '/paragraph/page'
Isn't solved

2022-06-07 12:10 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> +class imagealign extends ParagraphsBehaviorBase {
Read about CamelCase

2022-06-07 12:10 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> + *   id = "dummy_image_and_text",
isn't solved

2022-06-07 12:10 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> + *   description = @Translation("Allows to select image size and position."),
isn't solved

2022-06-07 12:10 UTC, Y0r commented on web/modules/custom/paragraph_align/src/Plugin/paragraphs/Behavior/imagealign.php
> +    $summary = [];
Isn;t solved

2022-06-07 12:11 UTC, Y0r commented on web/modules/custom/paragraph_align/paragraph_align.routing.yml
> +    _title: 'Welcome to My Module in Drupal 9'
Isn't solved

2022-06-14 08:38 UTC, Y0r approved these changes

2022-06-14 08:38 UTC, merged